
stages:
  - build
  - deploy
cache:
  paths:
    - node_modules/
yarn:
  image: node:latest    
  stage: build
  variables: 
    # Replace this with your site URL
    PUBLIC_URL: https://ucanr-it.gitlab.io/wucols-ui/
  script:
    - npm install
    - npm run-script --openssl-legacy-provider build
  artifacts:
    paths:
      - build/      
aws: 
  image: sleavely/node-awscli:12.x
  stage: deploy
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID 
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - echo pwd = $(pwd); ls; aws s3 cp --recursive ./build s3://wucols-plant-search-database-ui 
pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public         
  artifacts:
    paths:
      - public