stages:
  - build
  - deploy

yarn:
  image: node:latest    
  stage: build
  variables: 
    # Replace this with your site URL
    PUBLIC_URL: https://ucanr-it.gitlab.io/wucols-ui/
  script:
    - yarn install      
    - yarn build
  artifacts:
    paths:
      - build/      

pages:
  image: alpine:latest
  stage: deploy
  variables:
    GIT_STRATEGY: none        # Do not clone git repo
  script:
    # Rename the CRA `build` folder to `public`
    - mv build public         
  artifacts:
    paths:
      - public